# Application configuration for Docker environment
spring:
  application:
    name: todo-application

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/todoapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:todouser}
    password: ${SPRING_DATASOURCE_PASSWORD:todopass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    edu.icet.ecom: INFO
    org.springframework.web: INFO
